export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";

export const POSTS_FETCH_REQUEST = "POSTS_FETCH_REQUEST";
export const POSTS_FETCH_SUCCESS = "POSTS_FETCH_SUCCESS";
export const POSTS_FETCH_FAILURE = "POSTS_FETCH_FAILURE";

export const POST_FETCH_REQUEST = "POST_FETCH_REQUEST";
export const POST_FETCH_SUCCESS = "POST_FETCH_SUCCESS";
export const POST_FETCH_FAILURE = "POST_FETCH_FAILURE";

export const POST_CREATE_REQUEST = "NEWS_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "NEWS_CREATE_SUCCESS";
export const POST_CREATE_FAILURE = "NEWS_CREATE_FAILURE";

export const COMMENTS_FETCH_REQUEST = "COMMENTS_FETCH_REQUEST";
export const COMMENTS_FETCH_SUCCESS = "COMMENTS_FETCH_SUCCESS";
export const COMMENTS_FETCH_FAILURE = "COMMENTS_FETCH_FAILURE";

export const COMMENT_CREATE_FAILURE = "COMMENT_CREATE_FAILURE";
